services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resume_screener_db
    ports:
      - '5432:5432'
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: ./backend
    ports:
      - '8000:8000'  # Match Gunicorn port
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db
      - redis
    restart: always

  worker:
    build: ./backend
    command: poetry run celery -A celery_worker.celery worker -P gevent --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db
      - redis
    restart: always

volumes:
  postgres_data:
