"""Add required_years column to jobs table

Revision ID: d0a74cedb9b2
Revises: 5041d2fa38c3
Create Date: 2025-05-06 10:01:09.661222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a74cedb9b2'
down_revision = '5041d2fa38c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_years', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('required_years')

    # ### end Alembic commands ###
